### ISSUE TITLE
List chapters in the correct order

### ISSUE THREAD

**Issue by paul-buerkner** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#1]
The chapters below 10 are missing a leading zero so that the ordering of the chapters is messed up on github.

**Comment by ASKurz** [comment]
Thanks for the tip. Done.

**Comment by SimonDedman** [comment]
I could open a new issue I suppose but this title is perfect.
Chapters 1:4 are the same,
Chapter 5 is mostly the same but your 5.3 (multicollinearity) is his 6.1, and your 5.3.3 (post treatment bias) is his 6.2. Your 5.4 is then his 5.3 so it kinda lines back up again.
Thereafter it looks like your chapter 6 is his 7, your 8 his 9, etc.
I'm not sure the reasons for this (I'm still struggling to get my head around all of this, so a thousand thank-yous to you, Paul, Richard, and the countless others who contribute to making things easier to learn, you're giants, the lot of you), but maybe it would be good to have a quick line about the reordering of McElreath's chapters 5 & 6, at the top of your chapter 5? Presuming the reordering was a conscious choice by yourself. And presuming it was (and thus a reordering exercise doesn't cause everything to line up), it might be nice to add a dummy chapter 6, just so that subsequent chapters align.

(unrelated but since I'm typing)
Also, in [we have updates](https://bookdown.org/content/1850/index.html#we-have-updates), "The current solution for model 10.6 is wrong"... is now fixed according to the [link](https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse/issues/5) to that issue, so
A) Kudos, and
B) You can delete that line (and maybe others!) :smiley: 

Cheers!!

edit: ah jeez; I've just realised that I'm using McElreath's second edition, so it seems likely his page numbers & order has changed, not yours. Apologies!

**Comment by ASKurz** [comment]
I see your edit. No worries.

**Comment by SimonDedman** [comment]
Beard of Columbus. I didn't realise you had a V2 book - sincere apologies. On that one now. Cheers!

Edit: does look like the chapter numbers are still unsynched between McElreath v2 2019-12-08 & https://bookdown.org/content/3890/ 2020-10-11...
