### ISSUE TITLE
Exercise 12M3 help

### ISSUE THREAD

**Issue by ghost** [ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse#22]
Not an issue per se, so please close if this is not an appropriate venue to ask for help.

I'm having trouble implementing Exercise 12M3 in brms. Here's what I've done using the rethinking code:

     map2stan(
      alist(
        surv ~ dbinom(density, p) ,
        logit(p) <- alpha[tank],
        alpha[tank] ~ dcauchy(m, shape),
        m ~ dnorm(0, 10),
        shape ~ dcauchy(0, 1)
      ), data=chimpanzees )

But I can't figure how to apply `alpha[tank] ~ dcauchy(m, shape),` in `brms`. I was wondering if I should use the argument `family = binomial("cauchit")` within `brm` but it's not giving similar results. FWIW, I was able to replicate the results in `greta` with the following code:

    a <- normal(0, 1)
    sigma <- cauchy(0, 1, truncation = c(0, Inf))
    alpha_cauch <- cauchy(a, sigma, dim = max(reedfrog$tank))
    p_cauch <- ilogit(alpha_cauch)
    distribution(reedfrog$surv) <- binomial(reedfrog$density, p_cauch)

    m12greta_cauch <- model(alpha_cauch)
    m12m3_cauch_samples <- mcmc(m12greta_cauch)
    summary(m12m3_cauch_samples)

**Comment by ASKurz** [comment]
Ah, I see the difficulty. In Chapter 13.1 of my [bookdown project](https://bookdown.org/connect/#/apps/1850/access), check out the brief paragraph on McElreath’s **Rethinking: Why Gaussian?** box. In short, [brms only overtly supports using a Gaussian](https://github.com/paul-buerkner/brms/issues/231). But it does allow users to experiment with a Student’s *t*. So with brms, you’ll have to put either a very small prior on *nu* or otherwise fix it to 1. For more ideas on how to do that, check out my [project on robust Student *t* regression](https://github.com/ASKurz/Student-s-t_regression).

**Comment by ASKurz** [comment]
Are there any further difficulties, or might we close this issue?

**Comment by ghost** [comment]
Sorry, I admit I haven't had the time to work on it. I'll take it from here, and thanks for your help!

**Comment by ASKurz** [comment]
If you have any success with the method, do share. I'd love to hear about it.

**Comment by ghost** [comment]
Just to let you know, I've been playing around some more on this, and I was unfortunately unsuccessful in replicating the `greta` output.

**Comment by ASKurz** [comment]
Huh. Bummer. Thanks for the update, though.
